# Permalinks
permalink:        pretty

# Setup
title:            SWHYUN
tagline:          'Physics, Philosophy, and More.'
description:      'A blog exploring the boundaries of physics, philosophy, and more.'
url:              https://sw-hyun.github.io
baseurl:          /

author:
  name:           'Seungwon Hyun'
  url:            

paginate:         5

github:
  repo:           https://github.com/sw-hyun/sw-hyun.github.io