# Permalinks
permalink:        pretty

# Setup
title:            SWHYUN
tagline:          'Science and Technology'
description:      'A blog about science and technology.'
url:              https://sw-hyun.github.io
baseurl:          /

author:
  name:           'Seungwon Hyun'
  url:            

paginate:         5

github:
  repo:           https://github.com/sw-hyun/sw-hyun.github.io