# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SWHYUN
tagline:          'A blog about science and technology'
description:      'This is a blog where I talk about science and technology.'
url:              https://sw-hyun.github.io
baseurl:          /

author:
  name:           'Seungwon Hyun'
  url:            

paginate:         5

github:
  repo:           https://github.com/sw-hyun/sw-hyun.github.io
